eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: agents
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/agent/**
        - id: clients
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/client/**
        - id: otp
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/otp/**